### ISSUE TITLE
sleekxmpp.exceptions.IqTimeout in init_http

### ISSUE THREAD

**Issue by LNJ2** [zlaxy/jabbergram#1]
I got this error:
```
Please wait a couple of minutes until it's correctly connected
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bridge/env/lib/python3.5/site-packages/jabbergram-0.1.7-py3.5.egg/EGG-INFO/scripts/jabbergram.py", line 84, in init_http
  File "/home/bridge/env/lib/python3.5/site-packages/jabbergram-0.1.7-py3.5.egg/EGG-INFO/scripts/jabbergram.py", line 353, in discovery
  File "/home/bridge/env/lib/python3.5/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
sleekxmpp.exceptions.IqTimeout: <iq type="get" id="a10ec7aa-edb4-49db-a08b-e26b2a819bd9-1" to="kaidan.im" from="ghsqbridge@kaidan.im"><query xmlns="http://jabber.org/protocol/disco#items" /></iq>
```

**Comment by LNJ2** [comment]
```
diff --git a/jabbergram.py b/jabbergram.py
index 828ca3b..5df7126 100755
--- a/jabbergram.py
+++ b/jabbergram.py
@@ -12,7 +12,7 @@ import sleekxmpp
 import telegram
 from sleekxmpp.xmlstream.stanzabase import ElementBase
 from telegram.error import NetworkError, Unauthorized
-
+import ssl
 
 try:
     import requests
@@ -428,6 +428,7 @@ if __name__ == '__main__':
 
     xmpp = Jabbergram(jid, password, muc_rooms, nick, token, groups,
                       verify_ssl)
+    xmpp.ssl_version = ssl.PROTOCOL_SSLv23
     xmpp.register_plugin('xep_0045')
 
     if xmpp.connect():
```
This fixed it for me
